version: '3'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0.9-alpine3.17
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/data
    hostname: redis
  app:
    &app_base
    build: ./docker/app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/dev"
    ports:
      - '3000:3000'
    environment:
      PATH: /app/bin:/app/node_modules/.bin:/usr/local/bundle/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    volumes:
      - .:/app:delegated
      - app_bundle_volume:/usr/local/bundle
    working_dir: /app
    depends_on:
      - postgres
      - redis
    hostname: app
    privileged: true
    tty: true
    stdin_open: true

volumes:
  postgres_volume:
    driver: local
  redis_volume:
    driver: local
  app_bundle_volume:
    driver: local
